---
title: 'Ineqaulity task '
author: "zhipeng1"
date: "2021/10/31"
output: html_document 
---

```{r Load packages}
library(tidyverse)
library(sf)
library(here)
library(janitor)
library(countrycode)
library(tmap)
library(tmaptools)
library(OpenStreetMap)
library(maptools)
```

```{r read in data}
HDI <- read_csv(here::here("Data", "Gender Inequality Index (GII).csv"),
                       locale = locale(encoding = "latin1"),
                       na = "..", skip=5)
World <- st_read(here::here("Data", "World_Countries__Generalized_.shp"))

```

```{r select column}
HDIcols<- HDI %>%
  clean_names()%>%
  select(country, x2019, x2010)%>%
  mutate(difference=x2019-x2010)%>%
  slice(1:189,)%>%
  mutate(iso_code=countrycode(country, origin = 'country.name', destination = 'iso2c'))
```


```{r join}
Join_HDI <- World %>% 
  clean_names() %>%
  left_join(., 
            HDIcols,
            by = c("aff_iso" = "iso_code"))


```

```{r map, echo=FALSE, message=FALSE, warning=FALSE}
tmap_mode("view")
qtm(Join_HDI, 
    fill = "difference")
```

```{r better map havent finished}

tmapWorld <- Join_HDI %>%
  st_bbox(.) %>% 
  tmaptools::read_osm(., type = "osm", zoom = NULL)
a
install.packages("rosm")
library(rosm)
bg = osm.raster(Join_HDI)

tmap_mode("plot")

#tm_shape(Join_HDI)+
tm_rgb()+
#tm_shape(Life_expectancy4map)+ 
tm_polygons("difference", 
        style="pretty",
        palette="Blues",
        midpoint=NA,
        title="Number of years",
        alpha = 0.5) + 
  tm_compass(position = c("left", "bottom"),type = "arrow") + 
  tm_scale_bar(position = c("left", "bottom")) +
  tm_layout(title = "Difference in life expectancy", legend.position = c("right", "bottom"))
```

